# Generated by Django 4.2.10 on 2024-08-20 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="balance",
            name="unique_user_balance_string",
        ),
    ]
